# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-16 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0002_job_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.IntegerField(default=0),
        ),
    ]
